//
//  Country.swift
//  ECASChecker
//
//  Created by Roddy Munro on 29/03/2021.
//

import Foundation

struct Country: Identifiable {
    let id: String
    let name: String
}

extension Country {
    static let all: [Country] = [
        .init(id: "252", name: "Afghanistan"),
        .init(id: "199", name: "Africa NES"),
        .init(id: "401", name: "Aland Island"),
        .init(id: "081", name: "Albania"),
        .init(id: "131", name: "Algeria"),
        .init(id: "082", name: "Andorra"),
        .init(id: "151", name: "Angola"),
        .init(id: "620", name: "Anguilla"),
        .init(id: "621", name: "Antigua and Barbuda"),
        .init(id: "703", name: "Argentina"),
        .init(id: "049", name: "Armenia"),
        .init(id: "658", name: "Aruba"),
        .init(id: "299", name: "Asia NES"),
        .init(id: "305", name: "Australia"),
        .init(id: "399", name: "Australia NES"),
        .init(id: "011", name: "Austria"),
        .init(id: "050", name: "Azerbaijan"),
        .init(id: "035", name: "Azores"),
        .init(id: "622", name: "Bahamas"),
        .init(id: "253", name: "Bahrain"),
        .init(id: "412", name: "Bailwick of Jersey"),
        .init(id: "212", name: "Bangladesh"),
        .init(id: "610", name: "Barbados"),
        .init(id: "051", name: "Belarus"),
        .init(id: "012", name: "Belgium"),
        .init(id: "541", name: "Belize"),
        .init(id: "160", name: "Benin"),
        .init(id: "601", name: "Bermuda"),
        .init(id: "254", name: "Bhutan"),
        .init(id: "751", name: "Bolivia"),
        .init(id: "402", name: "Bonaire, Sint Eustatius, Saba"),
        .init(id: "048", name: "Bosnia and Herzegovina"),
        .init(id: "153", name: "Botswana"),
        .init(id: "403", name: "Bouvet Island"),
        .init(id: "709", name: "Brazil"),
        .init(id: "404", name: "British Indian Ocean Territory"),
        .init(id: "633", name: "British Virgin Islands"),
        .init(id: "255", name: "Brunei Darussalam"),
        .init(id: "083", name: "Bulgaria"),
        .init(id: "188", name: "Burkina Faso"),
        .init(id: "241", name: "Burma (Myanmar)"),
        .init(id: "154", name: "Burundi"),
        .init(id: "911", name: "Cabo Verde"),
        .init(id: "256", name: "Cambodia"),
        .init(id: "155", name: "Cameroon"),
        .init(id: "511", name: "Canada"),
        .init(id: "039", name: "Canary Islands"),
        .init(id: "624", name: "Cayman Islands"),
        .init(id: "157", name: "Central African Republic"),
        .init(id: "549", name: "Central America NES"),
        .init(id: "156", name: "Chad"),
        .init(id: "009", name: "Channel Islands"),
        .init(id: "721", name: "Chile"),
        .init(id: "202", name: "China"),
        .init(id: "200", name: "China (Hong Kong SAR)"),
        .init(id: "198", name: "China (Macao SAR)"),
        .init(id: "405", name: "Christmas Island"),
        .init(id: "722", name: "Colombia"),
        .init(id: "905", name: "Comoros"),
        .init(id: "840", name: "Cook Islands"),
        .init(id: "542", name: "Costa Rica"),
        .init(id: "043", name: "Croatia"),
        .init(id: "650", name: "Cuba"),
        .init(id: "406", name: "Curaçao"),
        .init(id: "221", name: "Cyprus"),
        .init(id: "015", name: "Czech Republic"),
        .init(id: "014", name: "Czechoslovakia"),
        .init(id: "158", name: "Democratic Rep. of Congo"),
        .init(id: "017", name: "Denmark"),
        .init(id: "183", name: "Djibouti"),
        .init(id: "625", name: "Dominica"),
        .init(id: "651", name: "Dominican Republic"),
        .init(id: "916", name: "East Timor"),
        .init(id: "753", name: "Ecuador"),
        .init(id: "101", name: "Egypt"),
        .init(id: "543", name: "El Salvador"),
        .init(id: "002", name: "England"),
        .init(id: "178", name: "Equatorial Guinea"),
        .init(id: "162", name: "Eritrea"),
        .init(id: "018", name: "Estonia"),
        .init(id: "161", name: "Ethiopia"),
        .init(id: "099", name: "Europe NES"),
        .init(id: "912", name: "Falkland Islands"),
        .init(id: "408", name: "Faroe Islands"),
        .init(id: "835", name: "Federated States of Micronesia"),
        .init(id: "801", name: "Fiji"),
        .init(id: "021", name: "Finland"),
        .init(id: "821", name: "Fr. South. and Antarctic Lands"),
        .init(id: "022", name: "France"),
        .init(id: "754", name: "French Guiana"),
        .init(id: "845", name: "French Polynesia"),
        .init(id: "163", name: "Gabon"),
        .init(id: "164", name: "Gambia"),
        .init(id: "052", name: "Georgia"),
        .init(id: "046", name: "German Democratic Republic"),
        .init(id: "024", name: "Germany, Federal Republic Of"),
        .init(id: "165", name: "Ghana"),
        .init(id: "084", name: "Gibraltar"),
        .init(id: "025", name: "Greece"),
        .init(id: "521", name: "Greenland"),
        .init(id: "626", name: "Grenada"),
        .init(id: "653", name: "Guadeloupe"),
        .init(id: "832", name: "Guam"),
        .init(id: "544", name: "Guatemala"),
        .init(id: "409", name: "Guernsey"),
        .init(id: "166", name: "Guinea"),
        .init(id: "167", name: "Guinea-Bissau"),
        .init(id: "711", name: "Guyana"),
        .init(id: "654", name: "Haiti"),
        .init(id: "410", name: "Heard and MacDonald Islands"),
        .init(id: "545", name: "Honduras"),
        .init(id: "204", name: "Hong Kong"),
        .init(id: "026", name: "Hungary"),
        .init(id: "085", name: "Iceland"),
        .init(id: "205", name: "India"),
        .init(id: "222", name: "Indonesia"),
        .init(id: "223", name: "Iran"),
        .init(id: "224", name: "Iraq"),
        .init(id: "027", name: "Ireland"),
        .init(id: "411", name: "Isle of Man"),
        .init(id: "206", name: "Israel"),
        .init(id: "028", name: "Italy"),
        .init(id: "169", name: "Ivory Coast"),
        .init(id: "602", name: "Jamaica"),
        .init(id: "207", name: "Japan"),
        .init(id: "225", name: "Jordan"),
        .init(id: "053", name: "Kazakhstan"),
        .init(id: "132", name: "Kenya"),
        .init(id: "831", name: "Kiribati"),
        .init(id: "257", name: "Korea, North (DPRK)"),
        .init(id: "258", name: "Korea, South"),
        .init(id: "064", name: "Kosovo"),
        .init(id: "226", name: "Kuwait"),
        .init(id: "054", name: "Kyrgyzstan"),
        .init(id: "260", name: "Laos"),
        .init(id: "019", name: "Latvia"),
        .init(id: "208", name: "Lebanon"),
        .init(id: "152", name: "Lesotho"),
        .init(id: "170", name: "Liberia"),
        .init(id: "171", name: "Libya"),
        .init(id: "086", name: "Liechtenstein"),
        .init(id: "020", name: "Lithuania"),
        .init(id: "013", name: "Luxembourg"),
        .init(id: "261", name: "Macao"),
        .init(id: "070", name: "Macedonia"),
        .init(id: "172", name: "Madagascar"),
        .init(id: "036", name: "Madeira"),
        .init(id: "111", name: "Malawi"),
        .init(id: "242", name: "Malaysia"),
        .init(id: "901", name: "Maldives"),
        .init(id: "173", name: "Mali"),
        .init(id: "030", name: "Malta"),
        .init(id: "833", name: "Marinas"),
        .init(id: "834", name: "Marshall Islands"),
        .init(id: "655", name: "Martinique"),
        .init(id: "174", name: "Mauritania"),
        .init(id: "902", name: "Mauritius"),
        .init(id: "906", name: "Mayotte"),
        .init(id: "501", name: "Mexico"),
        .init(id: "055", name: "Moldova"),
        .init(id: "087", name: "Monaco"),
        .init(id: "262", name: "Mongolia"),
        .init(id: "063", name: "Montenegro"),
        .init(id: "627", name: "Montserrat"),
        .init(id: "133", name: "Morocco"),
        .init(id: "175", name: "Mozambique"),
        .init(id: "122", name: "Namibia"),
        .init(id: "341", name: "Nauru"),
        .init(id: "264", name: "Nepal"),
        .init(id: "652", name: "Netherlands Antilles, The"),
        .init(id: "031", name: "Netherlands, The"),
        .init(id: "628", name: "Nevis"),
        .init(id: "822", name: "New Caledonia"),
        .init(id: "339", name: "New Zealand"),
        .init(id: "512", name: "Newfoundland, Dominion of"),
        .init(id: "546", name: "Nicaragua"),
        .init(id: "176", name: "Niger"),
        .init(id: "177", name: "Nigeria"),
        .init(id: "414", name: "Niue"),
        .init(id: "271", name: "North Vietnam"),
        .init(id: "006", name: "Northern Ireland"),
        .init(id: "830", name: "Northern Mariana Islands"),
        .init(id: "032", name: "Norway"),
        .init(id: "899", name: "Oceania NES"),
        .init(id: "263", name: "Oman"),
        .init(id: "209", name: "Pakistan"),
        .init(id: "213", name: "Palestinian Authority"),
        .init(id: "547", name: "Panama"),
        .init(id: "548", name: "Panama Canal Zone"),
        .init(id: "343", name: "Papau"),
        .init(id: "342", name: "Papua New Guinea"),
        .init(id: "755", name: "Paraguay"),
        .init(id: "723", name: "Peru"),
        .init(id: "227", name: "Philippines"),
        .init(id: "842", name: "Pitcairn Islands"),
        .init(id: "033", name: "Poland"),
        .init(id: "034", name: "Portugal"),
        .init(id: "656", name: "Puerto Rico"),
        .init(id: "265", name: "Qatar"),
        .init(id: "159", name: "Republic of Congo"),
        .init(id: "836", name: "Republic of Palau"),
        .init(id: "903", name: "Réunion"),
        .init(id: "088", name: "Romania"),
        .init(id: "056", name: "Russia"),
        .init(id: "179", name: "Rwanda"),
        .init(id: "915", name: "Saint Helena"),
        .init(id: "629", name: "Saint Kitts and Nevis"),
        .init(id: "630", name: "Saint Lucia"),
        .init(id: "531", name: "Saint Pierre and Miquelon"),
        .init(id: "407", name: "Saint-Barthelemy"),
        .init(id: "415", name: "Saint-Martin"),
        .init(id: "844", name: "Samoa"),
        .init(id: "843", name: "Samoa, American"),
        .init(id: "089", name: "San Marino"),
        .init(id: "914", name: "Sao Tome and Principe"),
        .init(id: "231", name: "Saudi Arabia"),
        .init(id: "007", name: "Scotland"),
        .init(id: "180", name: "Senegal"),
        .init(id: "061", name: "Serbia and Montenegro"),
        .init(id: "062", name: "Serbia, Republic of"),
        .init(id: "904", name: "Seychelles"),
        .init(id: "181", name: "Sierra Leone"),
        .init(id: "266", name: "Sikkim (Asia)"),
        .init(id: "246", name: "Singapore"),
        .init(id: "416", name: "Sint-Maarten"),
        .init(id: "016", name: "Slovakia"),
        .init(id: "047", name: "Slovenia"),
        .init(id: "825", name: "Soloman Islands"),
        .init(id: "824", name: "Solomon Islands"),
        .init(id: "182", name: "Somalia"),
        .init(id: "121", name: "South Africa, Republic of"),
        .init(id: "799", name: "South America NES"),
        .init(id: "189", name: "South Sudan"),
        .init(id: "037", name: "Spain"),
        .init(id: "201", name: "Sri Lanka"),
        .init(id: "631", name: "St. Vincent and the Grenadines"),
        .init(id: "185", name: "Sudan"),
        .init(id: "752", name: "Suriname"),
        .init(id: "186", name: "Swaziland"),
        .init(id: "040", name: "Sweden"),
        .init(id: "041", name: "Switzerland"),
        .init(id: "210", name: "Syria"),
        .init(id: "203", name: "Taiwan"),
        .init(id: "057", name: "Tajikistan"),
        .init(id: "130", name: "Tanzania"),
        .init(id: "267", name: "Thailand"),
        .init(id: "268", name: "Tibet (Autonomous Region)"),
        .init(id: "187", name: "Togo"),
        .init(id: "417", name: "Tokelau"),
        .init(id: "846", name: "Tonga"),
        .init(id: "605", name: "Trinidad and Tobago"),
        .init(id: "135", name: "Tunisia"),
        .init(id: "045", name: "Turkey"),
        .init(id: "058", name: "Turkmenistan"),
        .init(id: "632", name: "Turks and Caicos Islands"),
        .init(id: "826", name: "Tuvalu"),
        .init(id: "418", name: "U.S. Minor outlying Islands"),
        .init(id: "136", name: "Uganda"),
        .init(id: "001", name: "UK - British subject"),
        .init(id: "059", name: "Ukraine"),
        .init(id: "981", name: "UN specialized agency"),
        .init(id: "042", name: "Union Of Soviet Socialist Rep"),
        .init(id: "280", name: "United Arab Emirates"),
        .init(id: "461", name: "United States of America"),
        .init(id: "724", name: "Uruguay"),
        .init(id: "060", name: "Uzbekistan"),
        .init(id: "823", name: "Vanuatu"),
        .init(id: "090", name: "Vatican City State"),
        .init(id: "725", name: "Venezuela"),
        .init(id: "270", name: "Vietnam"),
        .init(id: "657", name: "Virgin Islands, U.S."),
        .init(id: "008", name: "Wales"),
        .init(id: "841", name: "Wallis and Futuna Is., Terr."),
        .init(id: "699", name: "West Indies NES"),
        .init(id: "184", name: "Western Sahara"),
        .init(id: "273", name: "Yemen"),
        .init(id: "274", name: "Yemen, People's Dem. Rep"),
        .init(id: "044", name: "Yugoslavia"),
        .init(id: "112", name: "Zambia"),
        .init(id: "113", name: "Zimbabwe")
    ]
}
